spring:
  datasource:
    driver-class-name: org.postgresql.Driverx
    url: jdbc:postgresql://localhost:5432/students_app
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
